### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jcelerier** [mapbox/jni.hpp#1]
When just including jni.hpp, with g++-6, I get an error at : 

    template < class R, class Subject, class... Args, R (*method)(JNIEnv&, Subject, Args...) >
    struct NativeMethodMaker< R (JNIEnv&, Subject, Args...), method >

The error : 

    ‘R(struct _JNIEnv&, Subject, Args ...)’ is not a valid type for a template non-type parameter
         struct NativeMethodMaker< R (JNIEnv&, Subject, Args...), method >
                                                                          ^

**Comment by jfirebaugh** [comment]
I believe this is a GCC bug. See [this SO question](http://stackoverflow.com/questions/37666268/gcc-function-wrapper-template-troubles). Would you be willing to submit a PR that uses one of the workarounds mentioned there?
