### ISSUE TITLE
Attempt to remove non-JNI local reference, dumping thread

### ISSUE THREAD

**Issue by tobrun** [mapbox/jni.hpp#18]
We have heard a couple of reports downstream in gl-native related to the following log message:

> Attempt to remove non-JNI local reference, dumping thread

Capturing from a Chromium issue:

> Whenever the parameters passed from Java to a JNI method (i.e. the incoming jobject parameters) are wrapped in a ScopedLocalJavaRef, this causes them to be deleted once they go out of scope with `JNIEnv::DeleteLocalRef`. On recent versions of ART with CheckJNI turned on, this causes a spammy warning to be printed to logcat stating `"Attempt to remove non-JNI local reference, dumping thread"` with a thread dump, as apparently parameters are not supposed to be deleted, only objects returned as local references from native->java JNI calls. **This is not actually a problem since the runtime just does nothing in this case (other than printing the warning)**

Discussion and related commits can be found in [chromium/506850](https://bugs.chromium.org/p/chromium/issues/detail?id=506850).

**Comment by jfirebaugh** [comment]
Can you open this as an issue in mapbox-gl-native? This will be an issue with use of jni.hpp, not with jni.hpp itself.

**Comment by tobrun** [comment]
I wrongly assumed that we need to fix up the `DeleteLocalRef` in this repository [codebase](https://github.com/mapbox/jni.hpp/search?utf8=%E2%9C%93&q=DeleteLocalRef&type=) first. 
Closing, will create a ticket in gl-native instead. Thank you for :eyes:'ing.

**Comment by tobrun** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/9688
