### ISSUE TITLE
Is there a way to add more method to native peer

### ISSUE THREAD

**Issue by spinorx** [mapbox/jni.hpp#24]
jni::RegisterNativePeer<Calculator>(env, jni::Class<Calculator>::Find(env), "peer",
        std::make_unique<Calculator, JNIEnv&>,
        "initialize",
        "finalize",
        METHOD(&Calculator::Add, "add"),
        METHOD(&Calculator::Subtract, "subtract"));

needs all method mapping to be specified in RegisterNativePeer.  Is there anyway to just specify constructor and initializer with this and add/attach methods one by one?

Why:
I have quite a few methods and the method is becoming long.  Also if there is error in signature mismatch its hard to trace which among these have the issue.

Was looking for something like:
ini::RegisterNativeMethod<Calculator>(
    env, jni::Class<Calculator>::Find(env),
    METHOD(&Calculator::Add, "add"));

**Comment by jfirebaugh** [comment]
Sure, you can call [this](https://github.com/mapbox/jni.hpp/blob/25a40bf707e462a9ff999c158c6f512215dbd48e/include/jni/native_method.hpp#L282) overload of `RegisterNativePeer` as many times as you want.

**Comment by spinorx** [comment]
Thank you.
