### ISSUE TITLE
jni::Object<> doesn't automatically cast from derived to base class

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/jni.hpp#25]
A `jni::Object<>` to a derived class does not lend itself to be easily cast down to a `jni::Object<>` to its base class:

```cpp
jni::Object<Derived> derived;
jni::Object<Base> base = child; // no viable conversion!
```

Compiler error:

```diff
-error: no viable conversion from 'Object<mbgl::android::VectorSource>' to 'Object<mbgl::android::Source>'
```

The workarounds require using `jni::Cast()` or using the raw pointer to create a new `jni::Object<>`:

```cpp
jni::Object<Derived> child;

jni::Object<Base> base = jni::Cast(env, derived, Base::javaClass);
    OR
jni::Object<Base> base = jni::Object<Base>(derived.Get())
```

**Comment by jfirebaugh** [comment]
The rule of thumb for templated wrapper classes like this is to allow implicit conversions of `Wrapper<D>` to `Wrapper<B>` when there's an implicit conversion from `D` to `B` or `D&` to `B&`. Maybe this would work for `Object<>` if you mirror the inheritance structure in Java with inheritance of C++ tag types.
