### ISSUE TITLE
Incorrect type signature code

### ISSUE THREAD

**Issue by berkus** [mapbox/jni.hpp#4]
Hi!

The code in https://github.com/mapbox/jni.hpp/blob/master/include/jni/type_signature.hpp#L43-L56 is incorrect.

It passes argument pack expansion as _arguments to the function_ DoNothingWith(). Per standard compiler is free to arrange function arguments computation in any order - and gcc and clang disagree here. Clang computes arguments left to right, producing correct signature; android gcc 4.9 computes them right to left, producing completely invalid function signature.

You can verify it [here](http://coliru.stacked-crooked.com/a/de1d04e2778a1cfc)

**Comment by jfirebaugh** [comment]
Thanks for the report! Since writing that code I learned a better technique for pack expansion but I forgot to port it to jni.hpp.

**Comment by berkus** [comment]
Yay, thanks for prompt fix!
