### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by kkaefer** [mapbox/jni.hpp#8]
* Why is `jni::Class` a standalone type rather than a class that inherits from `jni::Object` with a tag of `java/lang/Class<T>`?
* Should we add a a static cache to `Class::Find`?
* `jni.hpp` has an `ObjectTag`, but doesn't expose any of the Java functions on the `Object` object. are other object supposed to inherit from `jni::ObjectTag`?

**Comment by jfirebaugh** [comment]
> * Why is `jni::Class` a standalone type rather than a class that inherits from `jni::Object` with a tag of `java/lang/Class<T>`?

What's the advantage to inheriting? I'm not opposed to it if there's a good reason and covariant typing work out. (I don't think `java/lang/Class<T>` is a valid class name though; there are no generics at the JVM or JNI level.)

> * Should we add a a static cache to `Class::Find`?

No, I think jni.hpp is too low-level to have any built-in caching, and I'm not sure that `FindClass` is always guaranteed to return the same result for a given input in class loading corner cases.

> * `jni.hpp` has an `ObjectTag`, but doesn't expose any of the Java functions on the `Object` object. are other object supposed to inherit from `jni::ObjectTag`?

`ObjectTag` is just the tag class for `java/lang/Object`, nothing more. It's not meant to be inherited from. I'm not sure what you mean by "expose any of the Java functions on the `Object` object", can you provide an example?

**Comment by wang-bin** [comment]
try this https://github.com/wang-bin/JMI 
class, method and field can be cached
